server.port=${PORT:8085}
spring.thymeleaf.cache=false
spring.datasource.generate-unique-name=false
spring.main.allow-bean-definition-overriding=true

spring.data.mongodb.uri=mongodb+srv://adk0715_db_user:semG0xnqydedHeU3@java.cuhlpkk.mongodb.net/tacoclouddb

